-- CreateTable
CREATE TABLE `TechCategory` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `techName` VARCHAR(50) NOT NULL,
    `imgURL` VARCHAR(255) NOT NULL,
    `descripcion` VARCHAR(255) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
